spring:
  main:
    banner-mode: off
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
    hibernate:
      ddl-auto: validate

  flyway:
    clean-disabled: false # to disable cleaning of the database.
    clean-on-validation-error: false # to disable call clean when a validation error occurs.
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_history
    baselineOnMigrate: true
    validateOnMigrate: false